name: test-output-size

on:
 # push: 
 #   paths:
 #     - .github/workflows/test-output-size.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
      - uses: actions/checkout@v4
      - run: |
           ls -larth outputs
           MATLAB_OUTPUT=$(cat --squeeze-blank outputs)
           echo 'job-output<<EOF' >> $GITHUB_OUTPUT
           echo "$MATLAB_OUTPUT" >> $GITHUB_OUTPUT
           echo 'EOF' >> $GITHUB_OUTPUT
           ls -larth $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
