name: test-output-size

on:
 # push: 
 #   paths:
 #     - .github/workflows/test-output-size.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - run: |
         echo "value=1.0.0" >> "$GITHUB_OUTPUT"
        id: get_version

  deploy:
    needs: build  # Explicitly wait for build job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying ${{ needs.build.outputs.version }}"
