name: test-output-size

on:
 # push: 
 #   paths:
 #     - .github/workflows/test-output-size.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.value }}
    steps:
      - id: get_version
        run: |
           ls -larth outputs
           MATLAB_OUTPUT=$(cat --squeeze-blank outputs)
           echo 'job-output<<EOF' >> $GITHUB_OUTPUT
           echo "$MATLAB_OUTPUT" >> $GITHUB_OUTPUT
           echo 'EOF' >> $GITHUB_OUTPUT
           ls -larth $GITHUB_OUTPUT
       

