name: test-output-size

on:
 # push: 
 #   paths:
 #     - .github/workflows/test-output-size.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  print-context:
    runs-on: ubuntu-latest

    outputs:
      job-output: ${{ steps.test_gh-out.outputs.job-output }}
    steps:
      - uses: actions/checkout@v4
      - run: |
           ls -larth outputs.txt
           MATLAB_OUTPUT=$(cat --squeeze-blank outputs.txt)
           echo 'job-output<<EOF' >> $GITHUB_OUTPUT
           echo "$MATLAB_OUTPUT" >> $GITHUB_OUTPUT
           echo 'EOF' >> $GITHUB_OUTPUT
           echo 'test' 
           ls -larth $GITHUB_OUTPUT
        id: test_gh-out
